[package]
name = "sds011"
version = "0.1.0"
authors = ["Chris Ballinger <chrisballinger@gmail.com>"]

[[bin]]
name = "sds011"
doc = false

[dependencies]
serial = "0.4"
clap = "2.28.0"
# device = { git = "https://github.com/servo/devices", branch = "master" }